---
title: "graphics"
author: "Hannah Phan"
date: "March 20, 2020"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidycensus)
library(janitor)
library(gt)
library(haven)
library(infer)
library(fivethirtyeight)
options(scipen = 999)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
require(maps)
require(ggmap)
options(tigris_class = "sf")
library(tigris)
options(tigris_use_cache = TRUE)
library(gganimate)
theme_set(theme_bw())
library(imputeTS)
```

```{r data, include = FALSE, cache = T}
bluebikes <- read_csv("raw-data/current_bluebikes_stations.csv", skip = 1, col_types = cols()) %>%
  clean_names() %>%
  rename(Long = longitude,
         Lat = latitude) %>%
  na.omit()

streetlights <- read_csv("raw-data/streetlight-locations.csv", col_types = cols()) %>%
  clean_names() %>%
  rename(Long = long,
         Lat = lat) %>%
  na.omit()

parkboston2015 <- read_csv("raw-data/park-boston-monthly-transactions-by-zone-2015.csv", col_types = cols()) %>%
  clean_names()

parkingtickets2014 <- read_csv("raw-data/parking-tickets-portal-web-statistics.csv", col_types = cols()) %>%
  clean_names()

trafficdata2014 <- read_csv("raw-data/trafficdata.csv", col_types = cols())

trash <- read_csv("raw-data/big-belly-locations.csv", col_types = cols()) %>%
  clean_names() %>%
  na.omit() %>%
  separate(location, c("Long", "Lat"), sep = ", ")
#fix

crime <- read_csv("raw-data/tmpgwmn6nt4.csv", col_types = cols()) %>%
  na.omit()
  
trees <- read_csv("raw-data/Trees.csv", col_types = cols()) %>%
  na.omit() %>%
  rename(Long = X,
         Lat = Y)

hubway <- read_csv("raw-data/Hubway_Stations.csv", col_types = cols())
```

```{r all maps, echo = FALSE}
## I used instructions from
## https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html. I realized I only
## wanted to map within a specific latitudinal/longitudinal range because the
## bluebike data is only for the city of Boston. To determine the range, I
## sorted the bluebikes table by latitude in descending order, and then by
## longitude. Once I made the map, to plot the locations of the bikes, I used
## geom_point. I also added the locations for the streetlights in a separate
## map, but I realized there's a higher density of streetlights than bluebikes,
## so I'll need to restyle the map for the next milestone.

# I chose to use tidycensus for map of Boston and superimposed bike, tree, streetlight, and
# crime data over it.

# finding the average crime levels in areas with concentrated lights, bluebikes,
# trees, trash receptacles, traffic statistical aspect can come from calculating
# the densities, and then computing the correlation amongst densities. gganimate
# of crime over time. Color dots, or size the dots based off of severity of
# crime. Need to clean crime data to remove na values, maps for bikes and lights
# need to show points. Facet wrap by type of crime. Group crime by year.

census_api_key("9f9584127dd506cdaf80bdb78927e9c01c12f2b8", install = T, overwrite = T)

suffolk <- get_acs(geography = "tract",
                  variables = c(medincome = "B19013_001"), 
                  year = 2018,
                  state = "MA",
                  county = "Suffolk County",
                  geometry = TRUE)

suffolk_map <- suffolk %>%
  ggplot() +
  geom_sf() +
  coord_sf(xlim = c(-71.168, -71.005), ylim = c(42.266, 42.415), 
           expand = FALSE) +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  annotation_north_arrow(location = "bl", which_north = "true", 
                         pad_x = unit(0.1, "in"), pad_y = unit(5, "in"),
                         style = north_arrow_fancy_orienteering) +
  scale_x_continuous(breaks = seq(-71.16, -71.01, by = .03))


bluebike_map <- suffolk_map +
  ggtitle("Bluebike Map of Suffolk County, MA") +
  coord_sf(xlim = c(-71.168, -71.005), ylim = c(42.266, 42.415), 
           expand = FALSE) +
  geom_point(bluebikes, mapping = aes(Long, Lat), color = "blue") +
  scale_x_continuous(breaks = seq(-71.16, -71.01, by = .03))

streetlight_map <- suffolk_map +
  geom_sf(color = "black", fill = "black") +
  geom_point(streetlights, mapping = aes(Long, Lat), color = "yellow", alpha = 0.01) +
  labs(title = "Streetlight Map of Suffolk County, MA",
       caption = "Source: Boston Analyze Streetlight Data",
       x = "Longitude",
       y = "Latitude")

tree_map <- suffolk_map +
  geom_point(trees, mapping = aes(Long, Lat), color = "dark green", alpha = 0.01) +
  labs(title = "Tree Map of Suffolk County, MA",
       caption = "Source: Boston Analyze Public Tree Data 2011",
       x = "Longitude",
       y = "Latitude")

# trash_map <- suffolk_map +
#   geom_point(trees, mapping = aes(Long, Lat), color = "purple", alpha = 0.01) +
#  labs(title = "Trash Receptacle Map of Suffolk County, MA",
#       caption = "Source: Department of Innovation and Technology Public Big Belly Data")

crime_map <- suffolk_map +
  geom_sf(color = "black", fill = "lightgreen") +
  labs(title = "Crime Map of Suffolk County, MA",
       caption = "Source: ANALYZE BOSTON CRIME INCIDENT REPORTS (AUGUST 2015 - TO DATE)") +
  coord_sf(xlim = c(-71.168, -71.005), ylim = c(42.266, 42.415), 
           expand = FALSE) +
  geom_point(crime, mapping = aes(Long, Lat), color = "red", alpha = 0.3)

suffolk_map
bluebike_map
streetlight_map
tree_map
trash_map
crime_map

# look into cex argument to adjust size of the dots? check out social explorer
# or american census data to see how many commuters are in the area ACS survey,
# adjust alpha level = 0.5 to overlay the dots
# For milestone 6 try making a shiny app with an animated graph that shows the
# crime over the years

# https://gis.harvard.edu/
# https://www.r-bloggers.com/drug-crime-density-in-boston/
# https://stablemarkets.wordpress.com/2014/09/01/spatial-data-visualization-with-r/
# http://bcb.dfci.harvard.edu/~aedin/courses/R/CDC/maps.html 
# https://data.boston.gov/ 
```


```{r statistical graphs streetlights vs. crime}
# finding the average crime levels in areas with concentrated lights, bluebikes,
# trees, trash receptacles, traffic statistical aspect can come from calculating
# the densities, and then computing the correlation amongst densities. gganimate
# of crime over time. Color dots, or size the dots based off of severity of
# crime. Need to clean crime data to remove na values, maps for bikes and lights
# need to show points. Facet wrap by type of crime. Group crime by year.
# The most difficult aspect was calculating the densities. I needed to make a
# decision on how I wanted to segment the map to calculate the densities of each
# amenity for that segmented area. At first, I wanted to divide the map into a
# square grid and calculate the densities of each square, but then I realized
# that squares that included land outside of Suffolk County would inaccurately
# have a lower density of each amenity, so I made the decision to pick areas
# that only included Suffolk County, counting the number of amenities and
# dividing it by the count of each amenity to get the concentration/density.

crime_count_zone <- crime %>%
  mutate(zone = case_when(Long > -71.16 & Long < -71.13 & Lat > 42.26 & Lat < 42.28 ~ "z1",
    Long > -71.13 & Long < -71.10 & Lat > 42.26 & Lat < 42.28 ~ "z2",
    Long > -71.10 & Long < -71.07 & Lat > 42.26 & Lat < 42.28 ~ "z3",
    Long > -71.07 & Long < -71.04 & Lat > 42.26 & Lat < 42.28 ~ "z4",
    Long > -71.16 & Long < -71.13 & Lat > 42.28 & Lat < 42.3 ~ "z5",
    Long > -71.13 & Long < -71.10 & Lat > 42.28 & Lat < 42.3 ~ "z6",
    Long > -71.10 & Long < -71.07 & Lat > 42.28 & Lat < 42.3 ~ "z7",
    Long > -71.07 & Long < -71.04 & Lat > 42.28 & Lat < 42.3 ~ "z8",
    Long > -71.13 & Long < -71.10 & Lat > 42.3 & Lat < 42.32 ~ "z9",
    Long > -71.10 & Long < -71.07 & Lat > 42.3 & Lat < 42.32 ~ "z10",
    Long > -71.07 & Long < -71.04 & Lat > 42.3 & Lat < 42.32 ~ "z11",
    Long > -71.13 & Long < -71.10 & Lat > 42.32 & Lat < 42.34 ~ "z12",
    Long > -71.10 & Long < -71.07 & Lat > 42.32 & Lat < 42.34 ~ "z13",
    Long > -71.07 & Long < -71.04 & Lat > 42.32 & Lat < 42.34 ~ "z14",
    Long > -71.16 & Long < -71.13 & Lat > 42.34 & Lat < 42.36 ~ "z15",
    Long > -71.10 & Long < -71.07 & Lat > 42.34 & Lat < 42.36 ~ "z16",
    Long > -71.07 & Long < -71.04 & Lat > 42.34 & Lat < 42.36 ~ "z17",
    Long > -71.04 & Long < -71.01 & Lat > 42.34 & Lat < 42.36 ~ "z18",
    Long > -71.07 & Long < -71.04 & Lat > 42.36 & Lat < 42.38 ~ "z19",
    Long > -71.04 & Long < -71.01 & Lat > 42.36 & Lat < 42.38 ~ "z20",
    Long > -71.04 & Long < -71.01 & Lat > 42.38 & Lat < 42.40 ~ "z21")) %>%
  filter(!is.na(zone))

crime_count_histogram <- crime_count_zone %>%
  rename(Zone = zone) %>%
  ggplot(aes(Zone)) +
  geom_bar(stat = "count") +
  labs(title = "Crime Count per Zone in Suffolk, MA",
       subtitle = "Data From 2015 - Present",
       y = "Number of Crimes")

streetlight_count_zone <- streetlights %>%
  mutate(zone = case_when(Long > -71.16 & Long < -71.13 & Lat > 42.26 & Lat < 42.28 ~ "z1",
    Long > -71.13 & Long < -71.10 & Lat > 42.26 & Lat < 42.28 ~ "z2",
    Long > -71.10 & Long < -71.07 & Lat > 42.26 & Lat < 42.28 ~ "z3",
    Long > -71.07 & Long < -71.04 & Lat > 42.26 & Lat < 42.28 ~ "z4",
    Long > -71.16 & Long < -71.13 & Lat > 42.28 & Lat < 42.3 ~ "z5",
    Long > -71.13 & Long < -71.10 & Lat > 42.28 & Lat < 42.3 ~ "z6",
    Long > -71.10 & Long < -71.07 & Lat > 42.28 & Lat < 42.3 ~ "z7",
    Long > -71.07 & Long < -71.04 & Lat > 42.28 & Lat < 42.3 ~ "z8",
    Long > -71.13 & Long < -71.10 & Lat > 42.3 & Lat < 42.32 ~ "z9",
    Long > -71.10 & Long < -71.07 & Lat > 42.3 & Lat < 42.32 ~ "z10",
    Long > -71.07 & Long < -71.04 & Lat > 42.3 & Lat < 42.32 ~ "z11",
    Long > -71.13 & Long < -71.10 & Lat > 42.32 & Lat < 42.34 ~ "z12",
    Long > -71.10 & Long < -71.07 & Lat > 42.32 & Lat < 42.34 ~ "z13",
    Long > -71.07 & Long < -71.04 & Lat > 42.32 & Lat < 42.34 ~ "z14",
    Long > -71.16 & Long < -71.13 & Lat > 42.34 & Lat < 42.36 ~ "z15",
    Long > -71.10 & Long < -71.07 & Lat > 42.34 & Lat < 42.36 ~ "z16",
    Long > -71.07 & Long < -71.04 & Lat > 42.34 & Lat < 42.36 ~ "z17",
    Long > -71.04 & Long < -71.01 & Lat > 42.34 & Lat < 42.36 ~ "z18",
    Long > -71.07 & Long < -71.04 & Lat > 42.36 & Lat < 42.38 ~ "z19",
    Long > -71.04 & Long < -71.01 & Lat > 42.36 & Lat < 42.38 ~ "z20",
    Long > -71.04 & Long < -71.01 & Lat > 42.38 & Lat < 42.40 ~ "z21")) %>%
  filter(!is.na(zone))

streetlight_count_histogram <- streetlight_count_zone %>%
  rename(Zone = zone) %>%
  ggplot(aes(Zone)) +
  geom_bar(stat = "count") +
  labs(title = "Streetlight Count per Zone in Suffolk, MA",
       subtitle = "Data from Boston Analyze, 2020",
       y = "Number of Streetlights")

# To do a regression, I want to make a new table using pivot where the columns are the counts for crime, streetlights, bikes, etc., and the rows are the zones

crime_street_relation <- crime_streetlight %>%
  ggplot(., aes(Streetlights, Crimes)) +
  geom_point(color = "red") +
  geom_smooth(method = "lm", se = FALSE, formula = 'y ~ x') +
  labs(title = "Relationship Between Streetlight and Crime Densities",
       x = "Streetlights",
       y = "Crime Rates")

```

```{r statistical graphs trees vs. crime}
tree_count_zone <- trees %>%
  mutate(zone = case_when(Long > -71.16 & Long < -71.13 & Lat > 42.26 & Lat < 42.28 ~ "z1",
    Long > -71.13 & Long < -71.10 & Lat > 42.26 & Lat < 42.28 ~ "z2",
    Long > -71.10 & Long < -71.07 & Lat > 42.26 & Lat < 42.28 ~ "z3",
    Long > -71.07 & Long < -71.04 & Lat > 42.26 & Lat < 42.28 ~ "z4",
    Long > -71.16 & Long < -71.13 & Lat > 42.28 & Lat < 42.3 ~ "z5",
    Long > -71.13 & Long < -71.10 & Lat > 42.28 & Lat < 42.3 ~ "z6",
    Long > -71.10 & Long < -71.07 & Lat > 42.28 & Lat < 42.3 ~ "z7",
    Long > -71.07 & Long < -71.04 & Lat > 42.28 & Lat < 42.3 ~ "z8",
    Long > -71.13 & Long < -71.10 & Lat > 42.3 & Lat < 42.32 ~ "z9",
    Long > -71.10 & Long < -71.07 & Lat > 42.3 & Lat < 42.32 ~ "z10",
    Long > -71.07 & Long < -71.04 & Lat > 42.3 & Lat < 42.32 ~ "z11",
    Long > -71.13 & Long < -71.10 & Lat > 42.32 & Lat < 42.34 ~ "z12",
    Long > -71.10 & Long < -71.07 & Lat > 42.32 & Lat < 42.34 ~ "z13",
    Long > -71.07 & Long < -71.04 & Lat > 42.32 & Lat < 42.34 ~ "z14",
    Long > -71.16 & Long < -71.13 & Lat > 42.34 & Lat < 42.36 ~ "z15",
    Long > -71.10 & Long < -71.07 & Lat > 42.34 & Lat < 42.36 ~ "z16",
    Long > -71.07 & Long < -71.04 & Lat > 42.34 & Lat < 42.36 ~ "z17",
    Long > -71.04 & Long < -71.01 & Lat > 42.34 & Lat < 42.36 ~ "z18",
    Long > -71.07 & Long < -71.04 & Lat > 42.36 & Lat < 42.38 ~ "z19",
    Long > -71.04 & Long < -71.01 & Lat > 42.36 & Lat < 42.38 ~ "z20",
    Long > -71.04 & Long < -71.01 & Lat > 42.38 & Lat < 42.40 ~ "z21")) %>%
  filter(!is.na(zone))

tree_count_histogram <- tree_count_zone %>%
  rename(Zone = zone) %>%
  ggplot(aes(Zone)) +
  geom_bar(stat = "count") +
  labs(title = "Tree Count per Zone in Suffolk, MA",
       subtitle = "Data from Boston Analyze, 2020",
       y = "Number of Trees")

crime_tree_relation <- crime_tree %>%
  ggplot(., aes(Trees, Crimes)) +
  geom_point(color = "dark green") +
  geom_smooth(method = "lm", se = FALSE, formula = 'y ~ x') +
  labs(title = "Relationship Between Tree and Crime Densities",
       x = "Trees",
       y = "Crime Rates")
```

```{r statistical graphs bluebikes vs. crime}
bluebike_count_zone <- bluebikes %>%
  mutate(zone = case_when(Long > -71.16 & Long < -71.13 & Lat > 42.26 & Lat < 42.28 ~ "z1",
    Long > -71.13 & Long < -71.10 & Lat > 42.26 & Lat < 42.28 ~ "z2",
    Long > -71.10 & Long < -71.07 & Lat > 42.26 & Lat < 42.28 ~ "z3",
    Long > -71.07 & Long < -71.04 & Lat > 42.26 & Lat < 42.28 ~ "z4",
    Long > -71.16 & Long < -71.13 & Lat > 42.28 & Lat < 42.3 ~ "z5",
    Long > -71.13 & Long < -71.10 & Lat > 42.28 & Lat < 42.3 ~ "z6",
    Long > -71.10 & Long < -71.07 & Lat > 42.28 & Lat < 42.3 ~ "z7",
    Long > -71.07 & Long < -71.04 & Lat > 42.28 & Lat < 42.3 ~ "z8",
    Long > -71.13 & Long < -71.10 & Lat > 42.3 & Lat < 42.32 ~ "z9",
    Long > -71.10 & Long < -71.07 & Lat > 42.3 & Lat < 42.32 ~ "z10",
    Long > -71.07 & Long < -71.04 & Lat > 42.3 & Lat < 42.32 ~ "z11",
    Long > -71.13 & Long < -71.10 & Lat > 42.32 & Lat < 42.34 ~ "z12",
    Long > -71.10 & Long < -71.07 & Lat > 42.32 & Lat < 42.34 ~ "z13",
    Long > -71.07 & Long < -71.04 & Lat > 42.32 & Lat < 42.34 ~ "z14",
    Long > -71.16 & Long < -71.13 & Lat > 42.34 & Lat < 42.36 ~ "z15",
    Long > -71.10 & Long < -71.07 & Lat > 42.34 & Lat < 42.36 ~ "z16",
    Long > -71.07 & Long < -71.04 & Lat > 42.34 & Lat < 42.36 ~ "z17",
    Long > -71.04 & Long < -71.01 & Lat > 42.34 & Lat < 42.36 ~ "z18",
    Long > -71.07 & Long < -71.04 & Lat > 42.36 & Lat < 42.38 ~ "z19",
    Long > -71.04 & Long < -71.01 & Lat > 42.36 & Lat < 42.38 ~ "z20",
    Long > -71.04 & Long < -71.01 & Lat > 42.38 & Lat < 42.40 ~ "z21")) %>%
  filter(!is.na(zone))

bluebike_count_histogram <- bluebike_count_zone %>%
  rename(Zone = zone) %>%
  ggplot(aes(Zone)) +
  geom_bar(stat = "count") +
  labs(title = "Bluebike Count per Zone in Suffolk, MA",
       subtitle = "Data from Boston Analyze, 2020",
       y = "Number of Bluebikes")

crime_bluebike_relation <- crime_bluebike %>%
  ggplot(., aes(Bluebikes, Crimes)) +
  geom_point(color = "blue") +
  geom_smooth(method = "lm", se = FALSE, formula = 'y ~ x') +
  labs(title = "Relationship Between Bluebike and Crime Densities",
       x = "Bluebikes",
       y = "Crime Rates")

# look into taking the logs of the values, or coloring the regression lines by
# type of crime
```

```{r joined data}
crime_freq <- crime_count_zone %>%
  select(zone) %>%
  count(zone) %>%
  rename(Crimes = n)

streetlight_freq <- streetlight_count_zone %>%
  select(zone) %>%
  count(zone) %>%
  rename(Streetlights = n)

crime_streetlight <- full_join(crime_freq, streetlight_freq, by = "zone") %>%
  na_replace(fill = 0)

tree_freq <- tree_count_zone %>%
  select(zone) %>%
  count(zone) %>%
  rename(Trees = n)

crime_tree <- full_join(crime_freq, tree_freq, by = "zone") %>%
  na_replace(fill = 0)

bluebike_freq <- bluebike_count_zone %>%
  select(zone) %>%
  count(zone) %>%
  rename(Bluebikes = n)

crime_bluebike <- full_join(crime_freq, bluebike_freq, by = "zone") %>%
  na_replace(fill = 0)

joined_data <- full_join(crime_streetlight, crime_tree, by = c("zone", "Crimes")) %>%
  full_join(crime_bluebike, by = c("zone", "Crimes"))
```




```{r shinygraph, include = FALSE}

# To make my shiny app, I followed the same format as ps6 to save my desired
# graphic into a file in a folder in my repo and then rendered that image in the
# app.R file. I want to build onto this by adding animations.

suffolk_map %>%
ggsave(filename = file.path("final_project_shiny","suffolk_map.png"))

bluebike_map
streetlight_map
tree_map
trash_map
crime_map

crime_count_histogram

streetlight_count_histogram
crime_street_relation %>%
  ggsave(filename = file.path("final_project_shiny","crime_street_relation.png"))

tree_count_histogram
crime_tree_relation %>%
  ggsave(filename = file.path("final_project_shiny","crime_tree_relation.png"))

bluebike_count_histogram
crime_bluebike_relation %>%
  ggsave(filename = file.path("final_project_shiny","crime_bluebike_relation.png"))

logged_joined_data <- joined_data %>%
  filter(Crimes != 0 &
          Streetlights != 0 &
         Bluebikes != 0 &
         Trees != 0) %>%
  mutate(log_crimes = log(Crimes),
         log_streetlights = log(Streetlights),
         log_bluebikes = log(Bluebikes),
         log_trees = log(Trees)) %>%
  tidy(conf.int = T) %>%
  select(term, estimate, conf.low, conf.high)
  
  lm(log_crimes ~ log_streetlights * log_bluebikes * log_trees, data = .) %>%
       tidy(conf.int = T, conf.level = 0.90) %>%
       mutate_if(is.numeric, round, digits = 2) %>%
       clean_names() %>% 
       select(-std_error, -statistic, -p_value) %>% 
       rename("5th Percentile" = conf_low,
              "95th Percentile" = conf_high,
              "Coefficient" = estimate,
              "Term" = term) %>% 
       gt()
```
link to shiny app: https://hannah-phan.shinyapps.io/final_project_shiny/
